// You may modify this for testing purposes.
const data = [
	{
		// be able to search by gender height weight eye color occupation 
		//have different functions 
		//dob will be slightly different -age then convert from birthday 
		"id": 272822514,
		"firstName": "Billy",
		"lastName": "Bob",
		"gender": "male",
		"dob": "1/18/1949",
		"height": 71, 
		"weight": 175,
		"eyeColor": "brown",
		"occupation": "programmer",
		"parents": [],
		"currentSpouse": "Uma Bob is his wife ",
		"kids": ["Jill Pafoy is his daughter", " Ralph Bob is his son"]
	},
	{
		"id": 401222887,
		"firstName": "Uma",
		"lastName": "Bob",
		"gender": "female",
		"dob": "4/1/1947",
		"height": 65,
		"weight": 162,
		"eyecolor": "brown",
		"occupation": "assistant",
		"parents": [],
		"currentSpouse": "Billy Bob",
		"kids": ["Jill Pafoy is her daughter", " Ralph Bob is her son"]
	},
	{
		"id": 409574486,
		"firstName": "Michael",
		"lastName": "Walkens",
		"gender": "male",
		"dob": "5/9/1951",
		"height": 76,
		"weight": 250,
		"eyecolor": "brown",
		"occupation": "landscaper",
		"parents": [],
		"currentSpouse": "Jon Walkens is her husband" ,
		"kids": "Jasmine Bob is his daughter"
	},
	{
		"id": 260451248,
		"firstName": "Jon",
		"lastName": "Walkens",
		"gender": "male",
		"dob": "9/6/1945",
		"height": 62,
		"weight": 115,
		"eyecolor": "brown",
		"occupation": "assistant",
		"parents": [],
		"currentSpouse": "Michael Walkens is his wife",
		"kids": "Jasmine Bob is his daughter, Dave Pafoy is his son"
	},
	{
		"id": 629807187,
		"firstName": "Jack",
		"lastName": "Pafoy",
		"gender": "male",
		"dob": "3/16/1938",
		"height": 70,
		"weight": 207,
		"eyecolor": "black",
		"occupation": "nurse",
		"parents": [],
		"currentSpouse": "Jen Pafoy is his wife",
		"kids": "Annie Pafoy is his daughter, Dave Pafoy is his son"
	},
	{
		"id": 464142841,
		"firstName": "Jen",
		"lastName": "Pafoy",
		"gender": "female",
		"dob": "4/10/1940",
		"height": 72,
		"weight": 256,
		"eyecolor": "black",
		"occupation": "student",
		"parents": [],
		"currentSpouse": "Jack Pafoy" ,
		"kids": "Annie Pafoy is her daughter"
	},
	{
		"id": 982411429,
		"firstName": "Mister",
		"lastName": "Potatoo",
		"gender": "male",
		"dob": "12/18/1952",
		"height": 66,
		"weight": 170,
		"eyecolor": "hazel",
		"occupation": "architect",
		"parents": [],
		"currentSpouse": "Missuz Potatoo",
		"kids": []
	},
	{
		"id": 595767575,
		"firstName": "Missuz",
		"lastName": "Potatoo",
		"gender": "female",
		"dob": "10/28/1948",
		"height": 59,
		"weight": 137,
		"eyecolor": "blue",
		"occupation": "architect",
		"parents": [],
		"currentSpouse": "Mister Potatoo",
		"kids": []
	},
	{
		"id": 693243224,
		"firstName": "Joy",
		"lastName": "Madden",
		"gender": "female",
		"dob": "4/20/1939",
		"height": 69,
		"weight": 199,
		"eyecolor": "hazel",
		"occupation": "doctor",
		"parents": [],
		"currentSpouse": null,
		"kids": "Regina, Hana, Eloise, and Ellen Madden are her daughters and Mattias is her son",
	},
	{
		"id": 888201200,
		"firstName": "Mader",
		"lastName": "Madden",
		"gender": "male",
		"dob": "5/6/1937",
		"height": 76,
		"weight": 205,
		"eyecolor": "black",
		"occupation": "landscaper",
		"parents": [],
		"currentSpouse": null,
		"kids": "Regina, Hana, Eloise, and Ellen Madden are his daughters and Joey is his son"
	},
	{
		"id": 878013758,
		"firstName": "Jill",
		"lastName": "Pafoy",
		"gender": "female",
		"dob": "2/8/1972",
		"height": 74,
		"weight": 118,
		"eyecolor": "brown",
		"occupation": "programmer",
		"parents": "Uma Bob",
		"currentSpouse": "Dave Pafoy is her husband",
		"kids": []
	},
	{
		"id": 951747547,
		"firstName": "Ralph",
		"lastName": "Bob",
		"gender": "male",
		"dob": "12/23/1969",
		"height": 66,
		"weight": 179,
		"eyecolor": "blue",
		"occupation": "nurse",
		"parents": "Uma Bob",
		"currentSpouse": "Jasmine Bob",
		"kids": []
	},
	{
		"id": 159819275,
		"firstName": "Jasmine",
		"lastName": "Bob",
		"gender": "female",
		"dob": "12/18/1969",
		"height": 58,
		"weight": 156,
		"eyecolor": "blue",
		"occupation": "assistant",
		"parents": "Michael and Jon Walkens is her parents",
		"currentSpouse": "Ralph Bob",
		"kids": []
	},
	{
		"id": 348457184,
		"firstName": "Annie",
		"lastName": "Pafoy",
		"gender": "female",
		"dob": "11/4/1970",
		"height": 62,
		"weight": 235,
		"eyecolor": "hazel",
		"occupation": "landscaper",
		"parents": ["Jack Pafoy, Jen Pafoy"],
		"currentSpouse": null,
		"kids": []
	},
	{
		"id": 294874671, 
		"firstName": "Dave",
		"lastName": "Pafoy",
		"gender": "male",
		"dob": "8/5/1967",
		"height": 61,
		"weight": 112,
		"eyecolor": "green",
		"occupation": "doctor",
		"parents": ["Jack Pafoy , Jen Pafoy"],
		"currentSpouse": "Jill Pafoy" ,
		"kids": []
	}, 
	{
		"id": 931247228,
		"firstName": "Amii",
		"lastName": "Pafoy",
		"gender": "female",
		"dob": "3/13/1963",
		"height": 74,
		"weight": 184,
		"eyecolor": "brown",
		"occupation": "landscaper",
		"parents": ["Jack Pafoy, Jen Pafoy"],
		"currentSpouse": null,
		"kids": []
	},
	{
		"id": 822843554,
		"firstName": "Regina",
		"lastName": "Madden",
		"gender": "female",
		"dob": "7/26/1959",
		"height": 71,
		"weight": 249,
		"eyecolor": "brown",
		"occupation": "nurse",
		"parents": ["Joy Madden", "Mader Madden"],
		"currentSpouse": null,
		"kids": []
	},
	{
		"id": 819168108,
		"firstName": "Hana",
		"lastName": "Madden",
		"gender": "female",
		"dob": "10/7/1953",
		"height": 70,
		"weight": 187,
		"eyecolor": "brown",
		"occupation": "politician",
		"parents": ["Joy Madden", "Mader Madden"],
		"currentSpouse": null,
		"kids": []
	},
	{
		"id": 969837479,
		"firstName": "Eloise",
		"lastName": "Madden",
		"gender": "female",
		"dob": "12/11/1961",
		"height": 63,
		"weight": 241,
		"eyecolor": "brown",
		"occupation": "assistant",
		"parents": "Joy Madden, Mader Madden",
		"currentSpouse": null,
		"kids": []
	},
	{
		"id": 313207561,
		"firstName": "Mattias",
		"lastName": "Madden",
		"gender": "male",
		"dob": "2/19/1966",
		"height": 70,
		"weight": 110,
		"eyecolor": "blue",
		"occupation": "assistant",
		"parents": "Joy Madden, Mader Madden",
		"currentSpouse": "Ellen Madden",
		"kids": []
	},
	{
		"id": 313997561,
		"firstName": "Ellen",
		"lastName": "Madden",
		"gender": "female",
		"dob": "2/19/1970",
		"height": 67,
		"weight": 100,
		"eyecolor": "blue",
		"occupation": "doctor",
		"parents": [],
		"currentSpouse": "Mattias Madden",
		"kids": []
	},
	{
		"id": 313998000,
		"firstName": "Joey",
		"lastName": "Madden",
		"gender": "female",
		"dob": "2/02/1987",
		"height": 67,
		"weight": 100,
		"eyecolor": "blue",
		"occupation": "doctor",
		"parents": "Mattias madden, Ellen Madden",
		"currentSpouse": null,
		"kids": []
	}
];